// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigretionRoutingDemo.Models;

#nullable disable

namespace MigretionRoutingDemo.Migrations
{
    [DbContext(typeof(SalesDB))]
    partial class SalesDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MigretionRoutingDemo.Models.Customer", b =>
                {
                    b.Property<int>("CID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("CID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CID = 1,
                            City = "Aalborg",
                            Email = "MM@mail.dk",
                            Name = "Mark Marksen",
                            Phone = 74562819
                        },
                        new
                        {
                            CID = 2,
                            City = "Esbjerg",
                            Name = "Freja Frejsen",
                            Phone = 74579819
                        });
                });

            modelBuilder.Entity("MigretionRoutingDemo.Models.Order", b =>
                {
                    b.Property<int>("OID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OID"));

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OID");

                    b.HasIndex("CID");

                    b.HasIndex("PID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OID = 1,
                            CID = 2,
                            OrderDate = new DateTime(2024, 3, 12, 11, 20, 29, 501, DateTimeKind.Local).AddTicks(3705),
                            PID = 1,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("MigretionRoutingDemo.Models.Product", b =>
                {
                    b.Property<int>("PID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("PID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            PID = 1,
                            Name = "Gule Handker",
                            Price = 50
                        },
                        new
                        {
                            PID = 2,
                            Name = "Laptop",
                            Price = 5000
                        });
                });

            modelBuilder.Entity("MigretionRoutingDemo.Models.Order", b =>
                {
                    b.HasOne("MigretionRoutingDemo.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MigretionRoutingDemo.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("PID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MigretionRoutingDemo.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MigretionRoutingDemo.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
